### ISSUE TITLE
gawk dep?

### ISSUE THREAD

**Issue by ryzhovau** [gSpotx2f/ruantiblock#1]
[«Необходим gawk»](https://github.com/gSpotx2f/ruantiblock/blob/fc7517852367a729f4e0d53220545a5360621864/opt/usr/bin/ruantiblock.sh#L68). Значит, его тоже надо устанавливать дополнительно? Если да, тогда `PATH` парой строк выше должен начинаться с `/opt/bin`.

**Comment by gSpotx2f** [comment]
Не обращайте внимания =) Это я для себя комментировал. Для других дистрибутивов Linux (в Ubuntu, кажется, по умолчанию mawk), с busybox всё работает нормально...
