### ISSUE TITLE
ошибки при выполнении скрипта

### ISSUE THREAD

**Issue by StrikerBarmaley** [gSpotx2f/ruantiblock#11]
при выполнении ruantiblock.sh update
Device "ppp0" does not exist.
 ruantiblock update...
Connection error! (301) URL: https://reestr.rublacklist.net/api/v2/current/csv
подскажите как решить?

**Comment by gSpotx2f** [comment]
Смените источник блэклиста в `/opt/etc/ruantiblock/ruantiblock.conf`:
`BL_UPDATE_MODE="zapret-info"`

**Comment by StrikerBarmaley** [comment]
Device "ppp0" does not exist.  а это как поправить?

**Comment by gSpotx2f** [comment]
@StrikerBarmaley, указать корректный WAN интерфейс (тот через который идёт интернет-трафик от провайдера). Если у вас прямое соединение (IPoE) без PPP, то например у Asus RT-N56U B1 это eth3: `IF_WAN="eth3"`. У других девайсов может быть по другому. Если не можете определить, просто отключите опцию проксификации локального трафика роутера: `PROXY_LOCAL_CLIENTS=0`.
