### ISSUE TITLE
Проксификация VPN-клиентов сервера на роутере.

### ISSUE THREAD

**Issue by PlatonShubin** [gSpotx2f/ruantiblock#12]
Сам пытался разобраться, но не смог. Очень уж много нужно изучить... Запустил PPTP VPN-сервер на роутере, подключился с телефона. Но заблокированные сайты не проксируются для VPN-клиента, как для локальной сети. Я в целом хотел подключить так телефон, чтобы вообще он прозрачно находился в локалке, как будто дома. Появляется интерфейс ppp10 при подключении клиента, пытался перенаправить как-то сам, но вообще не смог разобраться в iptables и ipset. Может, поможете?.. Или даже функцию такую сделаете? Наверняка мне достаточно одной-двух команд для перенаправления трафика из ppp10 через Tor для сайтов из списка (использую только пользовательский).

**Comment by gSpotx2f** [comment]
У меня нет роутера с прошивкой Падавана и я не могу тестировать индивидуальные конфигурации с VPN-сервером и пр. Проблема клиентов VPN-сервера, похоже, в том, что обход блокировок работает только для локальной сети (в правиле iptables для ruantiblock в таблице nat есть определение входящего интерфейса `-i br0`). Попробуйте добавить такое же правило для интерфейса ppp10: `iptables -t nat -I PREROUTING 2 -i ppp10 -j ruantiblock`.
Чтобы всё работало и после перезагрузки, можно вообще убрать входящий интерфейс из правила iptables: замените в файле `/usr/bin/ruantiblock.sh` строку [124](https://github.com/gSpotx2f/ruantiblock/blob/7ab9d7aeea960f3c74d15ad67d0c2d3d6f92759e/opt/usr/bin/ruantiblock.sh#L124):

	IPT_FIRST_CHAIN_RULE="-i ${IF_IN} -j ${IPT_CHAIN}"

на

	IPT_FIRST_CHAIN_RULE="-j ${IPT_CHAIN}"

Если обход блокировок заработает для VPN-клиентов, то отпишитесь тут и я исправлю в репозитории...

**Comment by PlatonShubin** [comment]
Увы, не сработало. Правило iptables с ppp10 не дало эффекта, сообщение о блокировке уже не показывается, а показывается ERR_CONNECTION_REFUSED. То есть он наверно пытается, но не может трафик провести через тор. Менял ещё -i $(IF_IN) на -i ppp10, эффект такой же. Хотя при этом в локальной сети тоже работать не перестало почему-то... Убирал -i $(IF_IN), тоже не сработало.

При этом ping и traceroute работают. Но при, например curl получается connection refused. Может какие логи покидать?
<details><summary>ip a</summary>

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
2: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
    link/ether 40:31:3c:03:95:00 brd ff:ff:ff:ff:ff:ff
    inet 109.173.69.226/24 brd 109.173.69.255 scope global eth3
3: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN qlen 1000
    link/ether 40:31:3c:03:94:ff brd ff:ff:ff:ff:ff:ff
4: sit0: <NOARP> mtu 1480 qdisc noop state DOWN
    link/sit 0.0.0.0 brd 0.0.0.0
5: rai0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN qlen 1000
    link/ether 40:31:3c:03:95:02 brd ff:ff:ff:ff:ff:ff
6: ra0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UNKNOWN qlen 1000
    link/ether 40:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
7: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 40:31:3c:03:94:ff brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br0
8: rai1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 42:31:3c:00:95:02 brd ff:ff:ff:ff:ff:ff
9: wdsi0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:02 brd ff:ff:ff:ff:ff:ff
10: wdsi1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:02 brd ff:ff:ff:ff:ff:ff
11: wdsi2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:02 brd ff:ff:ff:ff:ff:ff
12: wdsi3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:02 brd ff:ff:ff:ff:ff:ff
13: apclii0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 42:31:3c:01:95:02 brd ff:ff:ff:ff:ff:ff
14: ra1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 42:31:3c:13:95:01 brd ff:ff:ff:ff:ff:ff
15: wds0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
16: wds1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
17: wds2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
18: wds3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 40:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
19: apcli0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 42:31:3c:03:95:01 brd ff:ff:ff:ff:ff:ff
137: ppp10: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1270 qdisc pfifo_fast state UNKNOWN qlen 3
    link/ppp
    inet 192.168.1.240 peer 192.168.1.241/32 scope global ppp10
```

</details>
<details><summary>iptables -t nat -L</summary>

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
ruantiblock  all  --  anywhere             anywhere
ruantiblock  all  --  anywhere             anywhere
vserver    all  --  anywhere             broadband-109-173-69-226.ip.moscow.rt.ru

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ruantiblock  all  --  anywhere             anywhere

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all  --  192.168.1.0/24       anywhere             to:109.173.69.226
SNAT       all  --  192.168.1.0/24       192.168.1.0/24       to:192.168.1.1

Chain ruantiblock (3 references)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             match-set onion dst redir ports 9040
REDIRECT   tcp  --  anywhere             anywhere             match-set ruantiblock-cidr dst redir ports 9040
REDIRECT   tcp  --  anywhere             anywhere             match-set ruantiblock-ip dst redir ports 9040
REDIRECT   tcp  --  anywhere             anywhere             match-set ruantiblock-dnsmasq dst redir ports 9040
```

</details>
Может дело в настройках тора? Вот такие настройки.
<details><summary>torrc</summary>

```
User platon
PidFile /opt/var/run/tor.pid
DataDirectory /tmp/var/lib/tor
Log notice file /opt/var/log/tor/notices.log
VirtualAddrNetwork 10.254.0.0/16    # Виртуальная подсеть для .onion ресурсов
AutomapHostsOnResolve 1
TransPort 192.168.1.1:9040          # Адрес LAN интерфейса
TransPort 127.0.0.1:9040
DNSPort 9053
#SOCKSPort 192.168.1.1:9050         # Адрес tor socks proxy в LAN для подключения браузера и пр.
GeoIPFile /opt/share/tor/geoip
GeoIPv6File /opt/share/tor/geoip6
ExcludeExitNodes {RU},{UA},{BY},{KZ},{MD},{TM},{UZ},{AM},{KG},{US},{CA}
ExitPolicy reject *:*
ExitPolicy reject6 *:*

UseBridges 1
ClientTransportPlugin obfs4 exec /opt/sbin/obfs4proxy managed
Bridge obfs4 83.19.141.94:9999 2BB1B4B9163E5F7B1C42A856F5B9A069ACC6DF30 cert=+fpduo4C8vsgCT5aSJJTYD+X2i1GQQteE9Pnjk9EnZ>...
Bridge obfs4 79.116.27.25:55556 2FE3DD008E511414DA20F5CEB442A5945544F669 cert=ipatWeQw3NEpiWccukhHb71OtzOPTb0rkwnfXJFGJ>...
Bridge obfs4 24.118.12.208:13043 4D3B06DE8359B06AAC7B85450631D799D76BB002 cert=ImEVRtnxA0TBOFkhpnBa53Ajed6NtcyGdsomA4fv>...
Bridge obfs4 212.227.149.187:443 255954D581ED2EAC3F5F54175A73EDC77E2D86D9 cert=7UVjND0qH1B/T0esYWxmGzvw00U6qOkifjDYBiGo>...
```

</details>

**Comment by gSpotx2f** [comment]
Используйте исправленный скрипт `/usr/bin/ruantiblock.sh`, без указания входящего интерфейса. Проверьте попадают ли пакеты VPN-клиентов в цепочку ruantiblock. Счётчики пакетов в цепочке ruantiblock должны увеличиваться при попытках VPN-клиента подключиться к заблокированному сайту:

	iptables -t nat -vL


> При этом ping и traceroute работают.

Пакеты ping и traceroute никогда не попадают в правила ruantiblock, в tor отправляются только TCP пакеты ([правило](https://github.com/gSpotx2f/ruantiblock/blob/7ab9d7aeea960f3c74d15ad67d0c2d3d6f92759e/opt/usr/bin/ruantiblock.sh#L125)). Просто провайдер пропускает пинги до заблокированных сайтов.

**Comment by PlatonShubin** [comment]
Выполнил `iptables -t nat -I PREROUTING 2 -i ppp10 -j ruantiblock` (это ведь одно и то же, что вх. интерфейс убрать?), пакеты совершенно точно попадают в цепочку. Число увеличивается быстро при спаме кнопки обновить страницу. Про пакеты тупанул, сам же видил, что переадресация только для TCP :)

**Comment by gSpotx2f** [comment]
В общем, в правилах iptables действие `REDIRECT --to-ports` перенаправляет пакеты на порт того же интерфейса с которого они пришли. Для пакетов локальной сети это интерфейс `br0` (192.168.1.1), т.е. пакеты на заблокированные сайты перенаправляются на 192.168.1.1:9040. Это тот адрес и порт, которые указаны в конфигурации Tor (`TransPort 192.168.1.1:9040`). В случае с VPN-клиентами пакеты приходят с `ppp10` (192.168.1.240) и пренаправляются на 192.168.1.240:9040, а на этом адресе Tor не работает. В этом причина сброса соединений VPN-клиентов. Можете попробовать настроить Tor на прослушивание адреса ppp10 (добавьте в конфиг Tor: `TransPort 192.168.1.240:9040`). Или на все доступные интерфейсы (`TransPort 0.0.0.0:9040`), но я не уверен что это сработает (к тому же не безопасно, потому что Tor будет слушать и `eth3`, т.е. может быть доступен из интернета).

**Comment by PlatonShubin** [comment]
Сработало! Прописал TransPort 192.168.1.240:9040. Это я так понимаю адрес ppp сервера. Далее прописал в функциях AddIptRules и RemIptRules `$IPT_CMD -t "$IPT_TABLE" -I "$IPT_FIRST_CHAIN" 2 -i ppp10 -j ${IPT_CHAIN}` и `$IPT_CMD -t "$IPT_TABLE" -D "$IPT_FIRST_CHAIN" -i ppp10 -j ${IPT_CHAIN}` соответственно. Думаю, можно даже прописать конфиги под такое дело, добавить ещё переменных, с например IF_PPP или типа того. В общем в таком виде впн клиенты тоже обходят блокировку! Но, одна проблема. Тор не запускается с ошибкой
```
Mar 19 02:55:28.390 [warn] Could not bind to 192.168.1.240:9040: Cannot assign requested address
Mar 19 02:55:28.391 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Mar 19 02:55:28.392 [err] Reading config failed--see warnings above.
```
если нет активного VPN- соединения, т.е. насколько я понимаю pppd выключен. Суть не знаю, в общем, как оно там устроено :) Но если есть активное соединение, то тор запускается нормально. Если потом соединение закрыть, то тор вроде не падает и при переподключении тоже всё работает. Как это исправить? Предполагаю, что надо что-то в автозапуск добавить, или типа того.

Ещё про безопасность не понял. на данном этапе она не упала? Или вы имели в виду, что только если нули указать для прослушивания прозрачного прокси, тогда плохо?

**Comment by gSpotx2f** [comment]
>Далее прописал в функциях AddIptRules и RemIptRules $IPT_CMD -t "$IPT_TABLE" -I "$IPT_FIRST_CHAIN" 2 -i ppp10 -j ${IPT_CHAIN} и $IPT_CMD -t "$IPT_TABLE" -D "$IPT_FIRST_CHAIN" -i ppp10 -j ${IPT_CHAIN} соответственно. Думаю, можно даже прописать конфиги под такое дело, добавить ещё переменных, с например IF_PPP или типа того.

Ненужно прописывать правила iptables для ppp10 в скрипт! Это не практично и неправильно. Просто [удалите локальный интерфейс из правила](https://github.com/gSpotx2f/ruantiblock/issues/12#issuecomment-1066144409) и тогда в цепочку `ruantiblock` будут попадать всё пакеты (со всех интерфейсов). Указание локального интерфейса - это дополнительный критерий, в нём нет жёсткой необходимости.

>Но, одна проблема. Тор не запускается с ошибкой

Всё верно, Tor выдаёт ошибку если не доступен IP-адрес указанный в конфиге. Сначала нужно запустить VPN-сервер, потом Tor.
Или можете попробовать заменить `TransPort 192.168.1.240:9040` на `TransPort 0.0.0.0:9040`, тогда Tor будет принимать соединения на всех доступных адресах (интерфейсах). В этом случае, обязательно добавьте парвила iptables для запрета доступа к Tor из вне (с интерфейса eth3, который у вас смотрит в интернет):

	iptables -t filter -I INPUT -i eth3 -p tcp -m tcp --dport 9040 -j DROP
	iptables -t filter -I INPUT -i eth3 -p udp -m udp --dport 9040 -j DROP

>Ещё про безопасность не понял. на данном этапе она не упала? Или вы имели в виду, что только если нули указать для прослушивания прозрачного прокси, тогда плохо?

Я имел в виду, что опасно запускать Tor с параметром `TransPort 0.0.0.0:9040` без запрета доступа к порту 9040 из вне (как объяснил выше)...

**Comment by PlatonShubin** [comment]
Окей, уберу просто входной интерфейс, но так ведь и запросы с eth3 будут попадать в цеполчку. Или нет? Не просто же так он изначально там указан... А как вот без прослушивания тором во все стороны сделать, чтоб работало? У меня pptp сервер, встроенный в прошивку. Настраивается через интерфейс роутера, собственно. Как мне его запустить до установления подключения? Это был бы самый простой вариант, если это возможно. В процессах, вижу, он висит как   `515 platon    1108 S    /usr/sbin/pptpd -c /etc/pptpd.conf`, но видимо порты при этом он себе не биндит?

**Comment by gSpotx2f** [comment]
>Окей, уберу просто входной интерфейс, но так ведь и запросы с eth3 будут попадать в цеполчку. Или нет? Не просто же так он изначально там указан...

Если всё работает без входного интерфейса, то это самый простой и универсальный вариант. Конечно, можете сделать как вам больше нравится, это не принципиально, главное чтобы работало... Если всё же будете использовать правила iptables для ppp10, то замените в них `ppp10` на `ppp+`: `iptables -t nat -I PREROUTING 2 -i ppp+ -j ruantiblock`. С eth3 могут попадать только входящие соединения, т.е. подключения из интернета к роутеру, и в этом случае адрес назначения этих пакетов (адрес eth3) не может быть в реестре. Эти пакеты просто пройдут сквозь цепочку `ruantiblock` как пакеты любых незаблокированных хостов. Кстати, в VPN-конфигурации (когда для обхода блокировок применяется OpenVPN вместо Tor) указать входящий интерфейс вообще невозможно и его там никогда небыло. Изначально интерфейс был как дополнительный ограничивающий критерий для стандартной конфигурации, где обход блокировок применяется только для локальной сети роутера. Это самый обычный и распространённый кейс. В вашем случае конфигурация с VPN-сервером нестандартная, и по хорошему, тут нужно что-то менять в самом скрипте.

>А как вот без прослушивания тором во все стороны сделать, чтоб работало? У меня pptp сервер, встроенный в прошивку. Настраивается через интерфейс роутера, собственно. Как мне его запустить до установления подключения? Это был бы самый простой вариант, если это возможно. В процессах, вижу, он висит как `515 platon 1108 S /usr/sbin/pptpd -c /etc/pptpd.conf`, но видимо порты при этом он себе не биндит?

Опять же, самый простой вариант - это прослушивание Tor всех интерфейсов, плюс правила iptables ограничивающие доступ к нему извне. Кстати, не уверен что это вообще сработает. Вы проверяли?
По поводу запуска pptpd и пр. я ничего не могу сказать, у меня нет роутера с прошивкой Падавана и я не помню как всё там выглядит. Наверное, можно Tor перезапускать каждый раз при подключении VPN-клиента (в веб-морде, вроде, можно добавлять команды выполняемые при подключении клиента?), но это жуткие костыли. Короче, попробуйте настроить конфигурацию с `TransPort 0.0.0.0:9040`, пусть Tor слушает все интерфейсы, и по идее, должен слушать и те которые появятся позже (ppp10)...

**Comment by PlatonShubin** [comment]
Ну пока работает, я наверно всё же так оставлю. Всё же изменения минимальные понадобились. Убрал br0 входящий интерфейс правила и добавил прослушивание 192.168.1.240, на котором у меня тор. По сути подключение хоть одного клиента VPN необходимо только для старта tor, который в общем-то сам никогда и не выключается. Так что при отключении/подключении новых клиентов ничего перезапускать не надо.
Спасибо большое за помощь!!!
