### ISSUE TITLE
Повторное обновление приводит к зависанию при нехватке памяти в /tmp

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock#2]
Есть проблема у роутеров с 32MB ОЗУ при установке во внутреннюю память. При старте роутера `ruantiblock.sh update` отрабатывает нормально, но в `/tmp` остается немного свободного места (чуть выше 4 МБ при `ALT_NSLOOKUP=0`) и если повторно запусть обновление, то роутер зависает (веб-интерфейс и ssh становятся недоступны), приходится жать reset. Если я правильно понял, при обновлении место в `/tmp/var/ruantiblock/` не освобождается (и при `ruantiblock.sh destroy` тоже). Возможно поможет включение модуля `zram` в прошивку, пока нет возможности проверить.

**Comment by gSpotx2f** [comment]
Во время обновления (когда скрипт-парсер скачивает и обрабатывает реестр) старые файлы, действительно, не удаляются. Это сделано для того, чтобы если обновление пройдёт неудачно или изменится сетевая конфигурация в момент обновления (при разрыве соединения с провайдером, например) не случилось ахтунга. Могу посоветовать лишь попробовать добавить в cron, за минуту до обновления ruantiblock, задание на удаление файлов из `/tmp/var/ruantiblock`, в качестве костыля...
Что-то типа (на примере из вики):

    59 4 */5 * * rm /tmp/var/ruantiblock/ruantiblock*
    0 5 */5 * * /etc/storage/ruantiblock.sh update

Вообще, 32мб мало для этого решения (для установки в /tmp)... Я тестировал на роутере с 128мб (RT-N56). А теперь ситуация стала ещё хуже в связи с добавленем в реестр CIDR диапазонов. Приходится использовать полный список (не только домены), а его размер уже под 20мб и только увеличивается, обработка ещё медленнее, оперативки жрёт ещё больше при обновлении... Такие дела...
