### ISSUE TITLE
Работа через TOR в варианте "Установка во внутреннюю память роутера"

### ISSUE THREAD

**Issue by svrgyj** [gSpotx2f/ruantiblock#3]
Доброго дня. Имеется wt3020 с работой wan через модем. Прошивка prometeus с tor, 3proxy, dnscrypt.  Свободного usb для entware нет, поэтому приходится использовать варианты обхода посредством нативных средств.
Можно ли добавить в ваш вариант скрипта для работы  "Установка во внутреннюю память роутера" возможность работы через tor?

**Comment by gSpotx2f** [comment]
Настраивайте tor из вашей прошивки в соответствии с конфигом https://github.com/gSpotx2f/ruantiblock/blob/master/opt/etc/tor/torrc. При установке во внутренню память `ruantiblock.sh` должен работать в режиме tor - `PROXY_MODE=1`. Разница между установкой в /opt и внутреннюю память - в нескольких переменных(в основном пути) и в использовании awk-модуля вместо lua. Разница между tor и VPN режимами только в значении переменной PROXY_MODE. Конкретно про прошивку prometeus ничего сказать не могу, ибо не имел с ней дела...

**Comment by svrgyj** [comment]
Все проделал по инструкции из wiki но никак не могу победить 

> /home/root # /etc/storage/ruantiblock.sh start
> /etc/storage/ruantiblock.sh: line 425: syntax error: unexpected "("
> /home/root # sh /etc/storage/ruantiblock.sh start
> /etc/storage/ruantiblock.sh: line 425: syntax error: unexpected "("
> 

Но кроме как параметры, ничего в скрипте не правил

P.S. prometeus как я понимаю скрипт основанный на прошивки padavan`а, который генерирует данную прошивку на большое количество роутеров отличных от asus. Собственно он так скажем "легален", сам разработчик padavan этот скрипт передал с условиями нераспространения готовых билдов прошивок и отказ от припроритарных компонентов.

**Comment by gSpotx2f** [comment]
Попробуйте скачать скрипт заново, может "побился" в процессе скачивания. Или скачайте весь репозиторий zip-архивом. Если заливаете на роутер с ПК по FTP, смотрите чтобы передача шла в текстовом режиме (а не в бинарном), иначе в конце строк будут лишние символы \r.
