### ISSUE TITLE
Реализация на RT-AC68U

### ISSUE THREAD

**Issue by KeyMag** [gSpotx2f/ruantiblock#4]
Не нашел способа с вами связаться, не подскажите что требуется для реализации на прошивке от Merlin? При использовании OpenVPN подключения.

**Comment by gSpotx2f** [comment]
Я с мерлиновской прошивкой не сталкивался, но подозреваю, что нужно смотреть пути в настройках и перезапуск dnsmasq `DNSMASQ_RESTART_CMD="/sbin/restart_dhcpd; /sbin/restart_dns"`. Вообще, не факт, что dnsmasq в мерлиновской прошивке умеет добавлять правила в ipset (это основной момент на котором строится само решение). Всё что касается iptables, ipset, awk, wget - оно везде одинаково работает. lua, вообще, ставится из entware...
