### ISSUE TITLE
Трафик до s3.amazonaws.com

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock#5]
Доброго дня. Не могу понять в чем причина. При скачивании с s3.amazonaws.com (52.216.x.y), например при скачивании [файла](https://github.com/rupor-github/fb2mobi/releases/download/3.6.63/fb2mobi_cli_linux_x86_64_glibc_2.23.tar.xz) трафик направляется через VPN-соединение, хотя в ipset-списке c CIDR таких сетей нет:
```
/home/root # ipset list ruab-cidr |grep '^52'
52.64.0.0/12
52.56.0.0/16
52.32.0.0/16
52.57.0.0/16
52.58.0.0/15
```
Примеры хостов 52.216.x.y:
```
/home/root # ipset list ruab
Name: ruab
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 150000 timeout 900
Size in memory: 228
References: 1
Number of entries: 3
Members:
54.231.98.176 timeout 896
52.216.129.115 timeout 887
52.216.192.16 timeout 876
```
Если остановить работу ruantiblock, то без VPN успешно скачивается — эти сети амазона не заблокированы.
В скрипте заменил ruantiblock на ruab для экономии размера .dnsmasq файла, остальное настроено по инструкции. Можете посмотреть, как у вас идет этот трафик?
```
/home/root # /etc/storage/ruantiblock.sh status

 ruab status: Active

  PROXY_MODE: 2
  DEF_TOTAL_PROXY: 0
  BLLIST_MODULE_CMD: /etc/storage/ruab.az-rbl.all.sh

  Last blacklist update:  06.06.2018-20:26 (ip: 20822 | CIDR: 67 | FQDN: 59546)

  Iptables rules:

   Match-set:  ruab-cidr
   Bytes:  13998

   Match-set:  ruab-ip
   Bytes:  12473

   Match-set:  ruab
   Bytes:  23906

  Ip sets:

   Name:  total-proxy
   Size in memory:  484
   Number of entries:  3

   Name:  ruab-cidr-tmp
   Size in memory:  316
   Number of entries:  0

   Name:  ruab-cidr
   Size in memory:  4012
   Number of entries:  67

   Name:  ruab-ip-tmp
   Size in memory:  60
   Number of entries:  0

   Name:  ruab-ip
   Size in memory:  339540
   Number of entries:  20822

   Name:  ruab
   Size in memory:  228
   Number of entries:  3

   Name:  onion
   Size in memory:  60
   Number of entries:  0
```

**Comment by gSpotx2f** [comment]
Дело не в cidr, срабатывает правило dnsmasq. Это следствие оптимизации списка доменов в модулях-парсерах (если кол-во доменов нижних ур-ней внесенных в реестр больше 16, то добавляется весь SLD вместо этих отдельных FQDN). Вот по этой причине SLD amazonaws.com добавляется в список dnsmasq целиком и доступ ко всем субдоменам идет через прокси. Нужно добавить amazonaws.com в исключения в переменной OPT_EXCLUDE_SLD в awk-модулях, или neverGroupSld в lua-модуле...
Вот так должно выглядеть:
`export OPT_EXCLUDE_SLD="livejournal.com facebook.com vk.com blog.jp msk.ru net.ru org.ru net.ua com.ua org.ua co.uk amazonaws.com"`
В lua-модуле:

    neverGroupSld = {
        ["livejournal.com"] = true,
        ["facebook.com"] = true,
        ["vk.com"] = true,
        ["blog.jp"] = true,
        ["msk.ru"] = true,
        ["net.ru"] = true,
        ["org.ru"] = true,
        ["net.ua"] = true,
        ["com.ua"] = true,
        ["org.ua"] = true,
        ["co.uk"] = true,
        ["amazonaws.com"] = true,
    },

Сделал коммит с исправлениями...
