### ISSUE TITLE
локальный трафик роутера

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock#6]
Здравствуйте. Если есть возможность, было бы неплохо добавить в скрипт возможность обрабатывать локальный трафик роутера через прокси/VPN (masquerade), например как описано здесь https://forum.ixbt.com/topic.cgi?id=14:64851:7927#7927
т.к. c роутера остаются недоступными заблокированные сервисы, в частности api.telegram.org и некоторые использующие хостинг AWS.

**Comment by gSpotx2f** [comment]
Добавил.
