### ISSUE TITLE
Отделение конфига от кода

### ISSUE THREAD

**Issue by kolyagora** [gSpotx2f/ruantiblock#8]
Спасибо, что продолжаете развивать проект.

Хочу предложить вынести настройки в отдельный файл, чтобы они не сбрасывались при обновлении скриптов. Либо, как вариант, предусмотреть возможность устанавливать значения параметров через переменные окружения.

**Comment by gSpotx2f** [comment]
Добавил внешний файл конфигурации. Придётся переустановить всё заново...
